version: '3.8'

networks:
  monitoring:

services:
  influxdb:
    image: influxdb:2.0.7
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - ./influxdb2:/var/lib/influxdb2
  grafana:
    image: grafana/grafana:9.0.4
    ports:
      - 3000:3000
    networks:
      - monitoring
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DATABASE_HOST=influxdb:8086
      - GF_DATABASE_NAME=mydb
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
